# Generated by Django 6.0.3 on 2026-03-12 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gemeinschaft',
                'verbose_name_plural': 'Gemeinschaften',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titel')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('majority_type', models.CharField(choices=[('simple', 'Einfaches Mehr (Köpfe)'), ('quota', 'Wertquoten-Mehrheit'), ('double', 'Doppeltes Mehr (Köpfe + Wertquoten)')], default='double', max_length=10, verbose_name='Mehrheitsart')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('open', 'Offen'), ('closed', 'Abgeschlossen')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Abstimmungsfrist')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='voting.community')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Antrag',
                'verbose_name_plural': 'Anträge',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=20, verbose_name='Einheitsnummer')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('quota', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Wertquote (‰)')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='voting.community')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Einheit',
                'verbose_name_plural': 'Einheiten',
                'ordering': ['unit_number'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('yes', 'Ja'), ('no', 'Nein'), ('abstain', 'Enthaltung')], max_length=10)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, verbose_name='Kommentar (optional)')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.proposal')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.unit')),
            ],
            options={
                'verbose_name': 'Stimme',
                'verbose_name_plural': 'Stimmen',
                'unique_together': {('proposal', 'unit')},
            },
        ),
    ]
