# Generated by Django 6.0.3 on 2026-03-13 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_unit_owner_nullable_invite_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposaldocument',
            options={'verbose_name': 'Dokument', 'verbose_name_plural': 'Dokumente'},
        ),
        migrations.AlterField(
            model_name='proposaldocument',
            name='file',
            field=models.FileField(upload_to='proposal_docs/'),
        ),
        migrations.AlterField(
            model_name='proposaldocument',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='proposaldocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='delegate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_delegations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_proxies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vote',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
